# Generated by Django 5.1.5 on 2025-05-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="tx_hash",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
