# Generated by Django 5.1.5 on 2025-05-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_sender_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sender",
            name="wallet_address",
            field=models.CharField(blank=True, default="", max_length=44, unique=True),
        ),
    ]
