# Generated by Django 5.2.4 on 2025-07-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_sender_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=44, null=True, unique=True),
        ),
    ]
