# Generated by Django 5.2.4 on 2025-08-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_sender_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='moonpay_transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('failed', 'failed'), ('completed', 'completed')], default='pending', max_length=10),
        ),
    ]
